.\" manpage for MySQL Guardian
.TH mysqlgd 1 "27 Jun 2019" "0.1" "MySQL Guardian Man Page"
.SH NAME
MySQL Guardian - Monitors MySQL and MariaDB Database Servers.
.SH SYNOPSIS
.B mysqlgd --["OPTION"]
.SH DESCRIPTION
MySQL Guardian is a daemon that monitors MySQL and MariaDB databases. Database servers are checked at configurable intervals to ensure they are online, responsive, and their databases are accessible. Database tables can also be checked to ensure their integrity. Guardian will also perform automated remote database backups.
.SH OPTIONS
.TP
.B -i --init
Create new /etc/mysqlgd.conf configuration file.
.TP
.B -g --gui
Launch the MySQL Guardian console control centre application.
.TP
.B -d --demonize
Launch the MySQL Guardian daemon to run in the background.
.TP
.B -a --add
Add a new MySQL or MariaDB database server to monitoring.
.TP
.B -r --remove [hostname]
Remove a database server from monitoring.
.TP
.B -e --exclude [hostname]
Exclude a database server from monitoring.
.TP
.B -i --include [hostname]
Include a database server in monitoring.
.TP
.B -l --list
List database servers currently in monitoring.
.TP
.B -s --status
List the status of all servers currently in monitoring.
.TP
.B -h --help
Display the help screen.
.SH AUTHOR
Alistair Packer (alistairpacker@yandex.com) and Stephen Planck (splanck9271@gmail.com)
.SH COPYRIGHT
.PP
GNU General Public License v3
.PP
Copyright (c) 2018-19 - Alistair Packer and Stephen Planck
